version: 0
formats:
  - htmlzip
  - pdf
conda:
  environment: docs/environment_docs.yml
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: True
