name: mbuild-docs
channels:
  - conda-forge
dependencies:
  - inkscape
  - ipykernel
  - ipywidgets
  - mock
  - nbsphinx
  - numpydoc
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-svg2pdfconverter
  - widgetsnbextension
