name: mosdef_gomc_docs
channels:
  - conda-forge
  - defaults
dependencies:
  - garnett
  - gsd
  - ipython
  - numpydoc
  - mock
  - sphinx_rtd_theme
  - nbsphinx
  - sphinxcontrib
  - pycifrw
  - pytest
  - pytest-cov
  - sympy
  - symengine
  - python-symengine
  - python>=3.9,<=3.10
  - forcefield-utilities>=0.2.1
  - foyer>=0.11.3
  - gmso>=0.9.1
  - mbuild>=0.16.0
  - pre-commit
  - sphinx
  - pip
  - pip:
      - bump2version
      - sphinxcontrib-svg2pdfconverter
      - sphinxcontrib-video
      - sphinxcontrib-serializinghtml
