name: mosdef_gomc
channels:
  - conda-forge
  - defaults
dependencies:
  - garnett
  - gsd
  - ipython
  - numpydoc
  - mock
  - sphinx_rtd_theme
  - nbsphinx
  - sphinxcontrib
  - pycifrw
  - sympy=1.10
  - python>=3.8,<=3.9
  - forcefield-utilities=0.2.1
  - foyer=0.11.3
  - gmso=0.9.1
  - mbuild=0.15.1
  - sphinx
  - pip
  - pip:
      - bump2version
      - sphinxcontrib-svg2pdfconverter
      - sphinxcontrib-video
      - sphinxcontrib-serializinghtml
